### ISSUE TITLE
`beam_search_rnn` missing from `myRNN`

### ISSUE THREAD

**Issue by tristanguigue** [JerrikEph/SentenceOrdering_PTR#1]
It looks like the function `beam_search_rnn` is missing from `myRNN`:

`from myRNN import beam_search_rnn`

Would it be possible to add it? Thanks!

**Comment by jingjing-gong** [comment]
Sorry for the delay, it's been updated. Forgot to update that one last time.

**Comment by JLUForever** [comment]
Would you please list the requirement of environment? I have met many problems when I try to run the code.
