### ISSUE TITLE
download data ‘Network is unreachable’

### ISSUE THREAD

**Issue by LINMouMouZiBo** [JerrikEph/SentenceOrdering_PTR#2]
I run the script getData.sh to download the training data, but get the error ‘Network is unreachable’; 
then I open the URL 'https://doc-14-3c-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0v3oorvakj8ov8hcnk9ta2h636moo4bs/1479139200000/12916301274912055673/*/0B-mnK8kniGAieXZtRmRzX2NSVDg?e=download' in chrome, the error code 403 was seen. 
Could you tell why I can't  download the data? I'm in China, Thank's! ^-^

**Comment by Stanxy** [comment]
I met the same problem too. I wonder if this link is associate with your account, so oursiders cannot visit the address

**Comment by jingjing-gong** [comment]
The api is obsolete download through this link: [https://drive.google.com/drive/folders/0B-mnK8kniGAiNVB6WTQ4bmdyamc](https://drive.google.com/drive/folders/0B-mnK8kniGAiNVB6WTQ4bmdyamc)
